import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/global/toaster";
import { AppHeader } from '@/components/header/app-header';
import { ConfiguratorProvider } from '@/context/ConfiguratorContext';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <ConfiguratorProvider>
          <AppHeader />
          {children}
          <Toaster />
        </ConfiguratorProvider>
      </body>
    </html>
  );
}